print ("ecuacion cuadratica")
print ("x = [ – b ± √(b^2 – 4ac) ] / 2a")
a = eval(input("ingrese el valor de a: "))
b = eval(input("ingrese el valor de b: "))
c = eval(input("ingrese el valor de c: "))
x_1 = ((-b)+(((b**2)-(4*(a*c)))**(1/2)))/(2*a)
x_2 = ((-b)-(((b**2)-(4*(a*c)))**(1/2)))/(2*a)
print (f"el valor de x1 es: {x_1}")
print (f"el valor de x2 es: {x_2}")