a= int(input("valor de a"))
b= int(input("valor de b"))
c= int(input("valor de c"))
x1=(-b+((b**2-4*a*c)**0.5)/(2*a))
x2=(-b-((b**2-4*a*c)**0.5)/(2*a))
print(" x1 es igual a:",x1)
print("x1 es igual a:",x2)
