numero1=float(input("digite el primer numero:"))
Numero2=float(input("digite el segundo numero:"))
print("empezamos con el primer numero",numero1,"y con el segundo numero",Numero2)
suma=(numero1+Numero2)
resta=(numero1-Numero2)
multiplicacion=(numero1*Numero2)              
divicion=(numero1/Numero2)
potencia=(numero1**Numero2)
print("la suma es:",suma)
print("la resta es:",resta)
print("la multiplicacion es:",multiplicacion)
print("la divicion es:",divicion)
print("la potencia es:",potencia)              
